//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMonitoringWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConfigID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int RecordInterval { get; set; }
        public Nullable<int> AuditDayOfWeek { get; set; }
        public Nullable<System.TimeSpan> AuditTimeStart { get; set; }
        public Nullable<System.TimeSpan> AuditTimeEnd { get; set; }
        public Nullable<decimal> AirPressurePrice { get; set; }
    }
}
