//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMonitoringWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnergyMonitoringContext : DbContext
    {
        public EnergyMonitoringContext()
            : base("name=EnergyMonitoringContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarm> Alarms { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<MailGroup> MailGroups { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<Sensor> Sensors { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<spGetLastDaysAvgRecords_Result> spGetLastDaysAvgRecords(Nullable<int> days)
        {
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLastDaysAvgRecords_Result>("spGetLastDaysAvgRecords", daysParameter);
        }
    
        public virtual ObjectResult<spGetLastDaysSumRecords_Result> spGetLastDaysSumRecords(Nullable<int> days)
        {
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLastDaysSumRecords_Result>("spGetLastDaysSumRecords", daysParameter);
        }
    
        public virtual ObjectResult<spGetSensors_Result> spGetSensors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSensors_Result>("spGetSensors");
        }
    
        public virtual ObjectResult<spGetFilterRecords_Result> spGetFilterRecords(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFilterRecords_Result>("spGetFilterRecords", startParameter, endParameter);
        }
    }
}
