//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMonitoringWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnergyMonitoringContext : DbContext
    {
        public EnergyMonitoringContext()
            : base("name=EnergyMonitoringContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarm> Alarms { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<Sensor> Sensors { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
    
        public virtual ObjectResult<SpGetAvgFlowEquipments_Result> SpGetAvgFlowEquipments(Nullable<int> year, Nullable<int> week, Nullable<int> weekday, Nullable<System.TimeSpan> timeStart, Nullable<System.TimeSpan> timeEnd)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var weekParameter = week.HasValue ?
                new ObjectParameter("week", week) :
                new ObjectParameter("week", typeof(int));
    
            var weekdayParameter = weekday.HasValue ?
                new ObjectParameter("weekday", weekday) :
                new ObjectParameter("weekday", typeof(int));
    
            var timeStartParameter = timeStart.HasValue ?
                new ObjectParameter("timeStart", timeStart) :
                new ObjectParameter("timeStart", typeof(System.TimeSpan));
    
            var timeEndParameter = timeEnd.HasValue ?
                new ObjectParameter("timeEnd", timeEnd) :
                new ObjectParameter("timeEnd", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetAvgFlowEquipments_Result>("SpGetAvgFlowEquipments", yearParameter, weekParameter, weekdayParameter, timeStartParameter, timeEndParameter);
        }
    
        public virtual ObjectResult<SpGetAvgFlowSum2_Result> SpGetAvgFlowSum2(Nullable<int> year, Nullable<int> weekday, Nullable<System.TimeSpan> timeStart, Nullable<System.TimeSpan> timeEnd)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var weekdayParameter = weekday.HasValue ?
                new ObjectParameter("weekday", weekday) :
                new ObjectParameter("weekday", typeof(int));
    
            var timeStartParameter = timeStart.HasValue ?
                new ObjectParameter("timeStart", timeStart) :
                new ObjectParameter("timeStart", typeof(System.TimeSpan));
    
            var timeEndParameter = timeEnd.HasValue ?
                new ObjectParameter("timeEnd", timeEnd) :
                new ObjectParameter("timeEnd", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetAvgFlowSum2_Result>("SpGetAvgFlowSum2", yearParameter, weekdayParameter, timeStartParameter, timeEndParameter);
        }
    
        public virtual ObjectResult<SpGetEquipmentsCount_Result> SpGetEquipmentsCount(Nullable<int> year, Nullable<int> weekday)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var weekdayParameter = weekday.HasValue ?
                new ObjectParameter("weekday", weekday) :
                new ObjectParameter("weekday", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetEquipmentsCount_Result>("SpGetEquipmentsCount", yearParameter, weekdayParameter);
        }
    
        public virtual ObjectResult<SpGetFilterAlarms_Result> SpGetFilterAlarms(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetFilterAlarms_Result>("SpGetFilterAlarms", startParameter, endParameter);
        }
    
        public virtual ObjectResult<SpGetFilterRecordsAvg_Result> SpGetFilterRecordsAvg(Nullable<System.DateTime> start, Nullable<System.DateTime> end, Nullable<int> groupId, Nullable<int> equipmentId)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(int));
    
            var equipmentIdParameter = equipmentId.HasValue ?
                new ObjectParameter("equipmentId", equipmentId) :
                new ObjectParameter("equipmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetFilterRecordsAvg_Result>("SpGetFilterRecordsAvg", startParameter, endParameter, groupIdParameter, equipmentIdParameter);
        }
    
        public virtual ObjectResult<SpGetSensors_Result> SpGetSensors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetSensors_Result>("SpGetSensors");
        }
    
        public virtual ObjectResult<SpGetMaxValues_Result> SpGetMaxValues(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetMaxValues_Result>("SpGetMaxValues", startParameter, endParameter);
        }
    }
}
