//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public device()
        {
            this.sensor = new HashSet<sensor>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string ip { get; set; }
        public Nullable<int> equipment_id { get; set; }
        public string lastModifiedBy { get; set; }
        public System.DateTime lastModifiedOn { get; set; }
        public string createdBy { get; set; }
        public byte[] createdOn { get; set; }
    
        public virtual equipment equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sensor> sensor { get; set; }
    }
}
