//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMonitoring
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnergyMonitoringEntities : DbContext
    {
        public EnergyMonitoringEntities()
            : base("name=EnergyMonitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<device> device { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<record> record { get; set; }
        public virtual DbSet<sensor> sensor { get; set; }
        public virtual DbSet<unit> unit { get; set; }
    }
}
