//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment()
        {
            this.device = new HashSet<device>();
        }
    
        public int id { get; set; }
        public string nr { get; set; }
        public string name { get; set; }
        public Nullable<int> location_id { get; set; }
        public string lastModifiedBy { get; set; }
        public System.DateTime lastModifiedOn { get; set; }
        public string createdBy { get; set; }
        public byte[] createdOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device> device { get; set; }
        public virtual location location { get; set; }
    }
}
