//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sensor()
        {
            this.record = new HashSet<record>();
        }
    
        public int id { get; set; }
        public int unit_id { get; set; }
        public int device_id { get; set; }
        public string lastModifiedBy { get; set; }
        public System.DateTime lastModifiedOn { get; set; }
        public string createdBy { get; set; }
        public byte[] createdOn { get; set; }
    
        public virtual device device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<record> record { get; set; }
        public virtual unit unit { get; set; }
    }
}
