//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMonitoringWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public long RecordID { get; set; }
        public decimal Value { get; set; }
        public int SensorID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Sensor Sensor { get; set; }
    }
}
